services:
#    leavesd.example:
#        class: LeaveSDBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    leavesd.download_info:
        class: LeaveSDBundle\Lib\DownloadInfo\LeaveSDDownloadInfo
        public: true
